name: branch_refresh

on:
  workflow_dispatch:
  push:
    #branches-ignore:
    #  - main

jobs:

  ubuntu-latest:
    runs-on: ubuntu-latest
    if: ${{ github.event.created == "true" }}
    steps:

      - name: checkout demo_repo_2 code
        uses: actions/checkout@master
      
      - name: exit on create event
        run: echo '${{ toJSON(github.event.created) }}'

      - name: Name Files
        id: name_file
        run: |
          FILENAME="myoutputfile.txt"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

      - name: Install dxtoolkit
        id: install_dxtoolkit
        run: |
          cat $GITHUB_ENV >> ${{ env.FILENAME }}
          ls -ld >> ${{ env.FILENAME }}
          ls -ltr >> ${{ env.FILENAME }}
          cd dxtoolkit2
          chmod 750 ./install.sh
          ./install.sh
          echo "`pwd`" >> ${{ env.FILENAME }}
          ls -ltr >> ${{ env.FILENAME }}
          cd ..
          echo "`pwd`" >> ${{ env.FILENAME }}

      - name: Execute API via Shell Script
        id: exec_shell
        run: |
          ./data_ops.sh -a refresh

      - name: Upload API Output log
        uses: actions/upload-artifact@v1
        with:
          name: apilog
          path: ${{ env.FILENAME }}
