name: branch_delete

on:
  delete

jobs:

  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo_repo_2 Code
        uses: actions/checkout@master
      - name: Name Files
        id: name_file
        run: |
          FILENAME="myoutputfile.txt"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV


      - name: Install dxtoolkit
        id: install_dxtoolkit
        run: |
          cat $GITHUB_ENV >> ${{ env.FILENAME }}
          ls -ld >> ${{ env.FILENAME }}
          ls -ltr >> ${{ env.FILENAME }}
          cd dxtoolkit2
          chmod 750 ./install.sh
          ./install.sh
          echo "`pwd`" >> ${{ env.FILENAME }}
          ls -ltr >> ${{ env.FILENAME }}
          cd ..
          echo "`pwd`" >> ${{ env.FILENAME }}

      - name: Execute API via Shell Script
        id: exec_shell
        run: |
          ./delete_env.sh 

      - name: Upload API Output log
        uses: actions/upload-artifact@v1
        with:
          name: apilog
          path: ${{ env.FILENAME }}
